### ISSUE TITLE
Add key storage details when using a browser

### ISSUE THREAD

**Issue by kdenhartog** [hyperledger/aries-staticagent-python#2]
Web Crypto API defines a safe method of storing key's in a browser. This could be a useful addition for static agents that are built in browser.

https://www.w3.org/TR/WebCryptoAPI/#concepts-key-storage

**Comment by dbluhm** [comment]
I totally agree but I'm not sure we'll ever use this library in the browser; maybe we should get an RFC going that outlines static agents and key storage best practices.

**Comment by TelegramSam** [comment]
I agree with @dbluhm. This is really great for js based static agents, but this agent (in python) won't ever be used that way.
