### ISSUE TITLE
Add Feature Discovery Support

### ISSUE THREAD

**Issue by TelegramSam** [hyperledger/aries-staticagent-python#4]
Add support for feature discovery to the StaticAgentConnection. This should report on any protocols that have registered handlers, including itself.
RFC for feature discovery protocol:
https://github.com/hyperledger/aries-rfcs/blob/master/features/0031-discover-features/README.md

The Indy Python Reference Agent can be used for testing: https://github.com/hyperledger/indy-agent/tree/master/python

Please reach out to @dbluhm and @TelegramSam with any questions.

**Comment by freemanjackal** [comment]
@dbluhm and @TelegramSam, Is it still help wanted? I am reading this:
 https://github.com/hyperledger/aries-rfcs/blob/master/features/0031-discover-features/README.md
and this:
https://github.com/hyperledger/aries-protocol-test-suite/blob/master/protocol_tests/discover_features/test_discover_features.py
I could give a try...

**Comment by dbluhm** [comment]
Happy to accept a PR on this if you're interested :slightly_smiling_face:

Feel free to reach out on chat.hyperledger.org (@dbluhm there as well) if you have any questions

**Comment by dbluhm** [comment]
As an update to the original comment, Aries Cloud Agent - Python (https://github.com/hyperledger/aries-cloudagent-python) is probably a better candidate for testing against than the now deprecated Indy Python Reference Agent. The test suite is also a good choice.
